version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - nginx_client
    networks:
      - frontend
      - server_backend_public
  nginx_client:
    image: nginx:alpine
    ports:
    - "82:81"
    volumes:
      - ./:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - frontend
networks:
  server_backend_public:
    external: true
  frontend: